services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    volumes:
      - wp_data:/var/www/html
    ports:
      - 80:81 
    depends_on:
      - db
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - wordpress_network
      
  db:
    image: mariadb:10.6-focal  # Uses a multi-architecture compatible MariaDB image
    container_name: wordpress_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
    networks:
      - wordpress_network

networks:
  wordpress_network:
    driver: bridge

volumes:
  db_data:
  wp_data:
